---
- name: Build dictionary of proxy users
  ansible.builtin.set_fact:
    __proxy_users: >-
      {%- set ns = namespace(port_count=0) -%}
      {%- set out = [] -%}
      {%- for proxy in role_iptvservice__credentials -%}
        {%- for proxy_user in proxy.proxy_users -%}
          {%- for provider in proxy.provider_credentials -%}
            {%- set ns.port_count = ns.port_count + 1 -%}
            {%- set d = {
              'provider_name': proxy.name,
              'provider_url': proxy.url,
              'proxy_name': proxy_user.name,
              'proxy_username': proxy_user.username,
              'proxy_pass': proxy_user.password,
              'proxy_port': role_iptvservice__proxy_start_port + ns.port_count,
              'xtream_account': provider.account,
              'xtream_user': provider.username,
              'xtream_pass': provider.password,
              'live': proxy_user.live | default('true'),
              'vod': proxy_user.vod | default('true')
            } -%}
            {%- set _ = out.append(d) -%}
          {%- endfor -%}
        {%- endfor -%}
      {%- endfor -%}
      {{ out }}
  tags:
    - always


- name: Include iptv_proxy tasks
  ansible.builtin.include_tasks:
    file: iptv_proxy.yml
    apply:
      tags:
        - iptvproxy
  tags:
    - iptvproxy


- name: Include haproxy tasks
  ansible.builtin.include_tasks:
    file: haproxy.yml
    apply:
      tags:
        - iptvproxy
  tags:
    - iptvproxy

- name: Include numconnections tasks
  ansible.builtin.include_tasks:
    file: numconnections.yml
  tags: [numconnections]

- name: Include dailyconnections tasks
  ansible.builtin.include_tasks:
    file: dailyconnections.yml
  tags: [dailyconnections]

- name: Include upstream_accounts tasks
  ansible.builtin.include_tasks:
    file: upstream_accounts.yml
  tags: [upstream_accounts]
